tasks:
  - before: go mod tidy && go install github.com/go-task/task/v3/cmd/task@latest && go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.50.1 && go install github.com/vektra/mockery/v2@latest && go install github.com/cloudwego/kitex/tool/cmd/kitex@latest && go install github.com/cloudwego/thriftgo@latest
  - init: npm install

vscode:
  extensions:
    - golang.go
    - usernamehw.errorlens
