version: '3'

services:
  mysql:
    image: 'mysql:latest'
    volumes:
      - ./pkg/configs/sql:/docker-entrypoint-initdb.d 
    ports:
      - 9910:3306
    environment:
      - MYSQL_DATABASE=gorm
      - MYSQL_USER=gorm
      - MYSQL_PASSWORD=gorm
      - MYSQL_RANDOM_ROOT_PASSWORD="yes"
  Etcd:
    image: "quay.io/coreos/etcd:v3.5.5"
    environment:
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
      - ETCDCTL_API=3
    ports:
      - 2379:2379