version: "3"

services:
  nginx-static:
    image: flashspys/nginx-static
    container_name: nginx-static
    ports:
      - 8081:80
    volumes: 
      - ./cmd/web/public:/static/public
  mysql:
    image: "mysql:latest"
    volumes:
      - ./pkg/initsql:/docker-entrypoint-initdb.d
    ports:
      - 9910:3306
    environment:
      - MYSQL_DATABASE=tik_duck
      - MYSQL_USER=tik_duck
      - MYSQL_PASSWORD=duck
      - MYSQL_RANDOM_ROOT_PASSWORD="yes"
  Etcd:
    image: "quay.io/coreos/etcd:v3.5.5"
    environment:
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
      - ETCDCTL_API=3
    ports:
      - 2379:2379
