version: "3"

dotenv: [".env", ".envrc"]

tasks:
  default:
    silent: true
    cmds:
      - task --list

  lint:
    silent: true
    desc: Run 'golangci-lint'
    cmds:
      - golangci-lint run --fix

  prettier:
    silent: true
    cmds:
      - npx prettier --write --list-different ./

  coverage:
    desc: Run tests with coverage report, used in CI.
    cmds:
      - go test -timeout 10s -tags test -race -coverpkg=./... -covermode=atomic -coverprofile=coverage.out ./...
