version: "3"

dotenv: [".env", ".envrc"]

tasks:
  default:
    silent: true
    cmds:
      - task --list

  lint:
    silent: true
    desc: Run 'golangci-lint'
    cmds:
      - golangci-lint run --fix
    