version: "3"

dotenv: [".env", ".envrc"]

tasks:
  default:
    silent: true
    cmds:
      - task --list

  lint:
    silent: true
    desc: Run 'golangci-lint'.
    cmds:
      - golangci-lint run --fix

  prettier:
    silent: true
    desc: Format config files.
    cmds:
      - npx prettier --write --list-different ./

  test:
    silent: true
    desc: Run tests without coverage report.
    cmds:
      - go test -gcflags="all=-l -N" -v ./...

  coverage:
    desc: Run tests with coverage report, used in CI.
    cmds:
      - go test -gcflags="all=-l -N" -timeout 10s -tags test -race -coverpkg=./... -covermode=atomic -coverprofile=coverage.out ./...
