// Code generated by Fastpb v0.0.2. DO NOT EDIT.

package minimal_demo

import (
	fmt "fmt"
	fastpb "github.com/cloudwego/fastpb"
)

var (
	_ = fmt.Errorf
	_ = fastpb.Skip
)

func (x *AddRequest) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_AddRequest[number], err)
}

func (x *AddRequest) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.A, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *AddRequest) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.B, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *AddResponse) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_AddResponse[number], err)
}

func (x *AddResponse) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Res, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *QueryRequest) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_QueryRequest[number], err)
}

func (x *QueryRequest) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Id, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *QueryResponse) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_QueryResponse[number], err)
}

func (x *QueryResponse) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Res, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *AddRequest) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	return offset
}

func (x *AddRequest) fastWriteField1(buf []byte) (offset int) {
	if x.A == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 1, x.A)
	return offset
}

func (x *AddRequest) fastWriteField2(buf []byte) (offset int) {
	if x.B == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 2, x.B)
	return offset
}

func (x *AddResponse) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *AddResponse) fastWriteField1(buf []byte) (offset int) {
	if x.Res == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 1, x.Res)
	return offset
}

func (x *QueryRequest) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *QueryRequest) fastWriteField1(buf []byte) (offset int) {
	if x.Id == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 1, x.Id)
	return offset
}

func (x *QueryResponse) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *QueryResponse) fastWriteField1(buf []byte) (offset int) {
	if x.Res == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 1, x.Res)
	return offset
}

func (x *AddRequest) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	return n
}

func (x *AddRequest) sizeField1() (n int) {
	if x.A == 0 {
		return n
	}
	n += fastpb.SizeInt64(1, x.A)
	return n
}

func (x *AddRequest) sizeField2() (n int) {
	if x.B == 0 {
		return n
	}
	n += fastpb.SizeInt64(2, x.B)
	return n
}

func (x *AddResponse) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *AddResponse) sizeField1() (n int) {
	if x.Res == 0 {
		return n
	}
	n += fastpb.SizeInt64(1, x.Res)
	return n
}

func (x *QueryRequest) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *QueryRequest) sizeField1() (n int) {
	if x.Id == 0 {
		return n
	}
	n += fastpb.SizeInt64(1, x.Id)
	return n
}

func (x *QueryResponse) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *QueryResponse) sizeField1() (n int) {
	if x.Res == 0 {
		return n
	}
	n += fastpb.SizeInt64(1, x.Res)
	return n
}

var fieldIDToName_AddRequest = map[int32]string{
	1: "A",
	2: "B",
}

var fieldIDToName_AddResponse = map[int32]string{
	1: "Res",
}

var fieldIDToName_QueryRequest = map[int32]string{
	1: "Id",
}

var fieldIDToName_QueryResponse = map[int32]string{
	1: "Res",
}
