// Code generated by Kitex v0.4.4. DO NOT EDIT.

package userplatservice

import (
	"context"
	userplat "github.com/808-not-found/tik_duck/kitex_gen/userplat"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	UserFavoriteAction(ctx context.Context, req *userplat.FavoriteActionRequest, callOptions ...callopt.Option) (r *userplat.FavoriteActionResponse, err error)
	UserFavoriteList(ctx context.Context, req *userplat.FavoriteListRequest, callOptions ...callopt.Option) (r *userplat.FavoriteListResponse, err error)
	UserCommentAction(ctx context.Context, req *userplat.CommentActionRequest, callOptions ...callopt.Option) (r *userplat.CommentActionResponse, err error)
	UserCommentList(ctx context.Context, req *userplat.CommentListRequest, callOptions ...callopt.Option) (r *userplat.CommentListResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kUserPlatServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kUserPlatServiceClient struct {
	*kClient
}

func (p *kUserPlatServiceClient) UserFavoriteAction(ctx context.Context, req *userplat.FavoriteActionRequest, callOptions ...callopt.Option) (r *userplat.FavoriteActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UserFavoriteAction(ctx, req)
}

func (p *kUserPlatServiceClient) UserFavoriteList(ctx context.Context, req *userplat.FavoriteListRequest, callOptions ...callopt.Option) (r *userplat.FavoriteListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UserFavoriteList(ctx, req)
}

func (p *kUserPlatServiceClient) UserCommentAction(ctx context.Context, req *userplat.CommentActionRequest, callOptions ...callopt.Option) (r *userplat.CommentActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UserCommentAction(ctx, req)
}

func (p *kUserPlatServiceClient) UserCommentList(ctx context.Context, req *userplat.CommentListRequest, callOptions ...callopt.Option) (r *userplat.CommentListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UserCommentList(ctx, req)
}
