// Code generated by Kitex v0.4.4. DO NOT EDIT.

package useruserservice

import (
	"context"
	useruser "github.com/808-not-found/tik_duck/IDLs/kitex_gen/useruser"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	UserRelationAction(ctx context.Context, req *useruser.RelationActionRequest, callOptions ...callopt.Option) (r *useruser.RelationActionResponse, err error)
	UserRelationFollowList(ctx context.Context, req *useruser.RelationFollowListRequest, callOptions ...callopt.Option) (r *useruser.RelationFollowListResponse, err error)
	UserRelationFollowerList(ctx context.Context, req *useruser.RelationFollowerListRequest, callOptions ...callopt.Option) (r *useruser.RelationFollowerListResponse, err error)
	UserRelationFriendList(ctx context.Context, req *useruser.RelationFriendListRequest, callOptions ...callopt.Option) (r *useruser.RelationFriendListResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kUserUserServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kUserUserServiceClient struct {
	*kClient
}

func (p *kUserUserServiceClient) UserRelationAction(ctx context.Context, req *useruser.RelationActionRequest, callOptions ...callopt.Option) (r *useruser.RelationActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UserRelationAction(ctx, req)
}

func (p *kUserUserServiceClient) UserRelationFollowList(ctx context.Context, req *useruser.RelationFollowListRequest, callOptions ...callopt.Option) (r *useruser.RelationFollowListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UserRelationFollowList(ctx, req)
}

func (p *kUserUserServiceClient) UserRelationFollowerList(ctx context.Context, req *useruser.RelationFollowerListRequest, callOptions ...callopt.Option) (r *useruser.RelationFollowerListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UserRelationFollowerList(ctx, req)
}

func (p *kUserUserServiceClient) UserRelationFriendList(ctx context.Context, req *useruser.RelationFriendListRequest, callOptions ...callopt.Option) (r *useruser.RelationFriendListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UserRelationFriendList(ctx, req)
}
