// Code generated by Kitex v0.4.4. DO NOT EDIT.

package chatservice

import (
	"context"
	chat "github.com/808-not-found/tik_duck/kitex_gen/chat"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetMsg(ctx context.Context, req *chat.MessageChatRequest, callOptions ...callopt.Option) (r *chat.MessageChatResponse, err error)
	PostMsg(ctx context.Context, req *chat.RelationActionRequest, callOptions ...callopt.Option) (r *chat.RelationActionResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kChatServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kChatServiceClient struct {
	*kClient
}

func (p *kChatServiceClient) GetMsg(ctx context.Context, req *chat.MessageChatRequest, callOptions ...callopt.Option) (r *chat.MessageChatResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetMsg(ctx, req)
}

func (p *kChatServiceClient) PostMsg(ctx context.Context, req *chat.RelationActionRequest, callOptions ...callopt.Option) (r *chat.RelationActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PostMsg(ctx, req)
}
