// Code generated by Kitex v0.4.4. DO NOT EDIT.

package userservice

import (
	"context"
	douyinuser "github.com/808-not-found/tik_duck/kitex_gen/douyinuser"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	User_Register(ctx context.Context, Req *douyinuser.DouyinUserRegisterRequest, callOptions ...callopt.Option) (r *douyinuser.DouyinUserRegisterResponse, err error)
	User_GetFeed(ctx context.Context, Req *douyinuser.DouyinFeedRequest, callOptions ...callopt.Option) (r *douyinuser.DouyinFeedResponse, err error)
	User_Login(ctx context.Context, Req *douyinuser.DouyinUserLoginRequest, callOptions ...callopt.Option) (r *douyinuser.DouyinUserLoginResponse, err error)
	User_Info(ctx context.Context, Req *douyinuser.DouyinUserInfoRequest, callOptions ...callopt.Option) (r *douyinuser.DouyinUserInfoResponse, err error)
	User_PublishList(ctx context.Context, Req *douyinuser.DouyinPublishListRequest, callOptions ...callopt.Option) (r *douyinuser.DouyinPublishListResponse, err error)
	User_PublishAction(ctx context.Context, Req *douyinuser.DouyinPublishActionRequest, callOptions ...callopt.Option) (r *douyinuser.DouyinPublishActionResponse, err error)
	User_Test(ctx context.Context, Req *douyinuser.DouyinTestinfo, callOptions ...callopt.Option) (r *douyinuser.DouyinTestinfo, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kUserServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kUserServiceClient struct {
	*kClient
}

func (p *kUserServiceClient) User_Register(ctx context.Context, Req *douyinuser.DouyinUserRegisterRequest, callOptions ...callopt.Option) (r *douyinuser.DouyinUserRegisterResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.User_Register(ctx, Req)
}

func (p *kUserServiceClient) User_GetFeed(ctx context.Context, Req *douyinuser.DouyinFeedRequest, callOptions ...callopt.Option) (r *douyinuser.DouyinFeedResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.User_GetFeed(ctx, Req)
}

func (p *kUserServiceClient) User_Login(ctx context.Context, Req *douyinuser.DouyinUserLoginRequest, callOptions ...callopt.Option) (r *douyinuser.DouyinUserLoginResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.User_Login(ctx, Req)
}

func (p *kUserServiceClient) User_Info(ctx context.Context, Req *douyinuser.DouyinUserInfoRequest, callOptions ...callopt.Option) (r *douyinuser.DouyinUserInfoResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.User_Info(ctx, Req)
}

func (p *kUserServiceClient) User_PublishList(ctx context.Context, Req *douyinuser.DouyinPublishListRequest, callOptions ...callopt.Option) (r *douyinuser.DouyinPublishListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.User_PublishList(ctx, Req)
}

func (p *kUserServiceClient) User_PublishAction(ctx context.Context, Req *douyinuser.DouyinPublishActionRequest, callOptions ...callopt.Option) (r *douyinuser.DouyinPublishActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.User_PublishAction(ctx, Req)
}

func (p *kUserServiceClient) User_Test(ctx context.Context, Req *douyinuser.DouyinTestinfo, callOptions ...callopt.Option) (r *douyinuser.DouyinTestinfo, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.User_Test(ctx, Req)
}
