// Code generated by Kitex v0.4.4. DO NOT EDIT.

package addservice

import (
	"context"
	minimal_demo "github.com/808-not-found/tik_duck/kitex_simple_demo/kitex_gen/minimal_demo"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Add(ctx context.Context, Req *minimal_demo.AddRequest, callOptions ...callopt.Option) (r *minimal_demo.AddResponse, err error)
	Query(ctx context.Context, Req *minimal_demo.QueryRequest, callOptions ...callopt.Option) (r *minimal_demo.QueryResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kAddServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kAddServiceClient struct {
	*kClient
}

func (p *kAddServiceClient) Add(ctx context.Context, Req *minimal_demo.AddRequest, callOptions ...callopt.Option) (r *minimal_demo.AddResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Add(ctx, Req)
}

func (p *kAddServiceClient) Query(ctx context.Context, Req *minimal_demo.QueryRequest, callOptions ...callopt.Option) (r *minimal_demo.QueryResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Query(ctx, Req)
}
