name: Test

on:
  push:
    branches-ignore:
      - renovate/**
    paths:
      - ".github/workflows/test.yaml"
      - "go.mod"
      - "go.sum"
      - "Taskfile.yaml"
      - "**.go"
      - "**.go.json"
  pull_request:
    branches:
      - master
    paths:
      - ".github/workflows/test.yaml"
      - "go.mod"
      - "go.sum"
      - "Taskfile.yaml"
      - "**.go"
      - "**.go.json"

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"

      - run: go mod tidy

      - name: Run tests
        run: task coverage

      - uses: codecov/codecov-action@v3
        with:
          files: coverage.out
